### ISSUE TITLE
Investigate OSGi problems

### ISSUE THREAD

**Issue by buep** [Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook#27]
In #24 we found problems installing the plugin on basically any Stash/Bitbucket server we tried on, and found it only works with `atlas-run`.

The problem we tried to mitigate in #26 by migrating to latest Bitbucket SDK template for plugins, as we thought that solved it.

It didn't - but we have narrowed it down now to be about OSGi which is something to do with how Bitbucket and other Atlassian tools deploy and run their plugins. Basically the isolate the plugin complete in it's own runtime, not even having access to Java classes on the system and from other plugins.
This means any dependency in the plugin needs to be bundled with the plugin to be available on runtime. With a few exceptions of their own dependencies.

But for us this means our dependency on the Tracey broker, protocol and commit message parser which is our own Github Java project, we need to ensure they are packaged and bundled with the plugin jar (or maybe OBR file).

These are the important references:

* https://developer.atlassian.com/server/framework/atlassian-sdk/managing-dependencies/
  * and under that you will find the specs for the bundle plugin http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html
* This explains how to bundly ones own libs into the plugin - **just like we want** - https://developer.atlassian.com/server/framework/atlassian-sdk/bundling-extra-dependencies-in-an-obr/
* More examples https://bitbucket.org/atlassian/atlassian-spring-scanner?_ga=2.24032952.345864942.1513856722-1874708957.1480102063
* Migrating from old style plugins in Atlassian world, to the OSGi bundle setup - explained here https://developer.atlassian.com/server/framework/atlassian-sdk/going-from-plugin-to-osgi-bundle/

**Comment by buep** [comment]
## Current status with Bitbucket 5.4.0

When I build https://github.com/Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook/tree/2ac0583bf2edc0b5d96b600ce7690327e7ecfc7b then I get about 17 Mb and 15 Mb jar and orb file.

When I upload them to Bitbucket it doesn't enable my plugin and it complains about missing OSGi wiring in the logs and missing dependencies.

```
2017-12-22 12:00:51,600 ERROR [UpmAsynchronousTaskManager:thread-2] admin @1RA724Gx720x44x0 huqpnz 172.17.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.p.o.f.OsgiPluginInstalledHelper Cannot determine required plugins, cannot resolve bundle 'net.praqma.stash.plugins.tracey.eiffel-rabbitmq-post-receive-hook'
2017-12-22 12:00:51,610 ERROR [UpmAsynchronousTaskManager:thread-2] admin @1RA724Gx720x44x0 huqpnz 172.17.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.plugin.osgi.factory.OsgiPlugin Detected an error (BundleException) enabling the plugin 'net.praqma.stash.plugins.tracey.eiffel-rabbitmq-post-receive-hook' : Unresolved constraint in bundle net.praqma.stash.plugins.tracey.eiffel-rabbitmq-post-receive-hook [127]: Unable to resolve 127.0: missing requirement [127.0] osgi.wiring.package; (osgi.wiring.package=com.atlassian.stash.commit).  This error usually occurs when your plugin imports a package from another bundle with a specific version constraint and either the bundle providing that package doesn't meet those version constraints, or there is no bundle available that provides the specified package. For more details on how to fix this, see https://developer.atlassian.com/x/mQAN
2017-12-22 12:00:51,610 WARN  [UpmAsynchronousTaskManager:thread-2] admin @1RA724Gx720x44x0 huqpnz 172.17.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.plugin.impl.AbstractPlugin Unable to enable plugin 'net.praqma.stash.plugins.tracey.eiffel-rabbitmq-post-receive-hook'
2017-12-22 12:00:51,623 WARN  [UpmAsynchronousTaskManager:thread-2] admin @1RA724Gx720x44x0 huqpnz 172.17.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.plugin.impl.AbstractPlugin Because of this exception
com.atlassian.plugin.osgi.container.OsgiContainerException: Cannot start plugin: net.praqma.stash.plugins.tracey.eiffel-rabbitmq-post-receive-hook
	at com.atlassian.plugin.osgi.factory.OsgiPlugin.enableInternal(OsgiPlugin.java:418)
	at com.atlassian.plugin.impl.AbstractPlugin.enable(AbstractPlugin.java:287)
	at com.atlassian.plugin.manager.PluginEnabler.actualEnable(PluginEnabler.java:130)
	at com.atlassian.plugin.manager.PluginEnabler.enable(PluginEnabler.java:107)
```

In my `MANIFEST.MF` I find in `target/classes/META-INF` I'm also missing my own dependencies, like the the tracey broker.


[MANIFEST.txt](https://github.com/Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook/files/1582410/MANIFEST.txt)

**Comment by buep** [comment]
With the above commti https://github.com/Praqma/tracey-bitbucket-eiffel-rabbitmq-post-receive-hook/commit/1cd5be6428e56d1e467136172ced02bba35dc74a I made some changes related to bundle in more of our dependencies trying to follow the references mentioned above to OSGi articles etc.

Then the obr file is 23 Mb almost, and the jar-file is 17 Mb still, so it is probably the obr file that needs to be installed.

The manifest file now also shows our dependencies as included now under `Embedded-Artifacts`, though not under `Import-package`

```
...
Created-By: Apache Maven Bundle Plugin
Embed-Dependency: *;scope=compile
Embedded-Artifacts: tracey-protocol-eiffel-2eddc78f98.jar;g="com.github.
 Praqma";a="tracey-protocol-eiffel";v="2eddc78f98",commit-message-parser
 -8834a4b0fe.jar;g="com.github.Praqma";a="commit-message-parser";v="8834
 a4b0fe",tracey-broker-1.2.1.jar;g="com.github.Praqma";a="tracey-broker"
 ;v="1.2.1",slf4j-api-1.7.2.jar;g=".org.slf4j";a="slf4j-api";v="1.7.2",s
 lf4j-simple-1.7.2.jar;g="org.slf4j";a="slf4j-simple";v="1.7.2",atlassia
 n-spring-scanner-annotation-1.2.6.jar;g="com.atlassian.plugin";a="atlas
 sian-spring-scanner-annotation";v="1.2.6",gson-2.2.2-atlassian-1.jar;g=
 "com.google.code.gson";a="gson";v="2.2.2-atlassian-1"
Import-Package: org.springframework.osgi.service.exporter.
...
```
There is a warning about unused import package instructions, so this is why they are not found under 
`Import-Package` as they are automatically removed I guess.

When I upload tho obr file to Bitbucket it can't load the plugin, but this time it seems to be missing some other dependencies and be more about our old code is not compatible with the Bitbucket server (async hook might be deprecated)

Error log:

```
...
2017-12-22 12:17:59,581 WARN  [ThreadPoolAsyncTaskExecutor::Thread 22]  c.a.p.s.s.util.ProductFilterUtil Couldn't detect product, will use ProductFilter.ALL
2017-12-22 12:17:59,635 ERROR [ThreadPoolAsyncTaskExecutor::Thread 22]  c.a.p.s.s.e.ComponentImportBeanFactoryPostProcessor Unable to load class 'com.atlassian.stash.commit.CommitService' for component importation purposes.  Skipping...
2017-12-22 12:17:59,635 ERROR [ThreadPoolAsyncTaskExecutor::Thread 22]  c.a.p.s.s.e.ComponentImportBeanFactoryPostProcessor Unable to load class 'com.atlassian.stash.server.ApplicationPropertiesService' for component importation purposes.  Skipping...
2017-12-22 12:18:00,533 ERROR [UpmAsynchronousTaskManager:thread-2] admin @1HN96I0x737x44x0 d0sqmd 172.17.0.1 "POST /rest/plugins/1.0/ HTTP/1.1" c.a.p.manager.DefaultPluginManager There was an error loading the descriptor 'Eiffel Rabbit MQ Post Receive Hook' of plugin 'net.praqma.stash.plugins.tracey.eiffel-rabbitmq-post-receive-hook'. Disabling.
java.lang.NoClassDefFoundError: com/atlassian/stash/hook/repository/AsyncPostReceiveRepositoryHook
	at java.lang.ClassLoader.defineClass1(Native Method)
	at com.atlassian.plugin.module.ClassPrefixModuleFactory.getModuleClass(ClassPrefixModuleFactory.java:44)
	at com.atlassian.plugin.module.PrefixDelegatingModuleFactory.guessModuleClass(PrefixDelegatingModuleFactory.java:145)
...
`

So to move forward now I think we need to switch the plugin to be a bitbucket plugin template and latest dependencies, then we might have solved the OSGi issues.

**Comment by buep** [comment]
@kryptag I'll deliver these changes to the master branch, you need to pull in those changes from the pom.xml file into your work on #26 so we get them into our new Bitbucket plugin setup. I think that will solve some of the dependency problems we have there.
